---
title: "Présentation de projet OPEN Groupe 2"
author: "Camille BONNET, Gabriel BURELLIER et Jiwar LAEBOUSSE"
date: "2024-02-12"
output: pdf_document

---

# Auteurs

Camille BONNET, Gabriel BURELLIER et Jiwar LAEBOUSSE.

# OPEN to the world

## Le concept

*OPEN to the world* est une application de voyage. L'utilisateur renseigne sur une première page différentes informations le concernant et l'application lui trouve la destination idéale pour ses prochaines vacances.

## Les critères étudiés

L'application demande dans un premier temps à l'utilisateur de rentrer son Nom et Prénom.
Ensuite différentes informations sont demandées afin d'affiner les conseils donnés:


-   Nombre de voyageur
-   Catégories d'ages
    -   enfant en bas age
    -   enfant 
    -   adolescent 
    -   jeune adulte 
    -   adulte 
    -   sénior
-   Durée du séjour
-   Budjet
-   Période de l'année
-   Type de destination
    -   pays chaud
    -   pays froid
    -   pays tempéré
    -   peu m'importe
-   Types de destinations
    -   pays chaud
    -   pays froid
    -   pays tempéré
    -   peu m'importe
-   Types d'activités 
    -   culturelles
    -   sportives
    -   détentes
    -   familliales
    -   festives

## Les conseils donnés

A partir des donées récoltées, l'application proposera un pays à visiter et suggérera des activités.

Par exemple, pour un couple d'une vingtaine d'année qui souhaite faire un voyage culturel d'une semaine au mois d'avril dans un pays chaud, avec un budjet moyen, l'application pourrait lui proposer une visite guidée de Lisbonne au Portugal. 

## Pistes d'améliorations

Il existe de multiples pistes d'amélioration pour notre application. Tout d'abord, il serrait bien d'élargir considérablement la liste des destinations que nous proposons.En effet, nous nous sommes limité à une trentaine de pays.

Nous pourrions envisager d'affiner nos conseils en ciblant nos propositions sur des villes plutot que sur des pays et en indiquant différents services comme des photos, des hotels, des locations de voitures ou des liens pour reserver des activités...

Il serait également intéréssant de faire apparaitre une carte du monde qui pointerait la destination choisie.

Fin

